export const TYPES = {
    LOGIN_AUTH_VALUE: `@@login/AUTH_VALUE`,
    LOGIN_DO_LOGIN: `@@login/DO_LOGIN`,
    LOGIN_LOGIN_START: `@@login/LOGIN_START`,
    LOGIN_LOGIN_FAILED: `@@login/LOGIN_FAILED`,
    LOGIN_LOGIN_SUCCESS: `@@login/LOGIN_SUCCESS`,
};
